Repository DARMA-tasking/vt, pull requests merged in 2019-10, with the labels that each got.

#495 458 compile clang 8.0
  src/vt/group/group_info.h
  src/vt/group/region/group_range.h
  src/vt/messaging/listener.h
  src/vt/rdma/rdma.cc
  src/vt/sequence/sequencer.h
  src/vt/termination/termination.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
  src/vt/vrt/collection/balance/greedylb/greedylb.h
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
  src/vt/vrt/collection/balance/lb_invoke/invoke.cc
  src/vt/vrt/collection/balance/lb_invoke/invoke.h
  src/vt/vrt/collection/balance/proc_stats.impl.h
  src/vt/vrt/collection/balance/rotatelb/rotatelb.h
  src/vt/vrt/collection/dispatch/dispatch.h
  src/vt/vrt/collection/holders/col_holder.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/context/context_vrtinfo.cc
  src/vt/vrt/context/context_vrtinfo.h
Labels: 1.0.0

#479 478 Fix tracing bugs in objgroup and colliding method names
  src/vt/registry/auto/auto_registry.cc
  src/vt/trace/trace_event.cc
  src/vt/trace/trace_event.h
  src/vt/trace/trace_registry.h
Labels: 1.0.0, 1.0.0-beta.1

#505 470 work around icc bug
  src/vt/termination/interval/integral_set.h
Labels: 1.0.0, 1.0.0-beta.1

#508 507 LB add barriers to synchronize the hierlb tree setup
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
  src/vt/vrt/collection/balance/hierarchicallb/hierlb_msgs.h
Labels: 1.0.0, 1.0.0-beta.1

#509 1.0.0 beta.2 proposed update
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
  src/vt/vrt/collection/balance/hierarchicallb/hierlb_msgs.h
Labels: 1.0.0, 1.0.0-beta.2

#473 472 Convert MPI_Recv to async MPI_Irecv
  src/vt/messaging/active.cc
  src/vt/messaging/active.h
  src/vt/messaging/irecv_holder.h
Labels: 1.0.0

#513 512 Fix clang warning in tests due to gtest macro
  tests/unit/collection/test_broadcast.cc
  tests/unit/collection/test_construct.cc
  tests/unit/collection/test_construct_idx_fst.cc
  tests/unit/collection/test_construct_idx_snd.cc
  tests/unit/collection/test_construct_no_idx.cc
  tests/unit/collection/test_index_types.cc
  tests/unit/collection/test_send.cc
  tests/unit/location/test_location.cc
  tests/unit/memory/test_memory_active.cc
Labels: 1.0.0, 1.0.0-beta.3

#516 515 Fix memory use-after-free bug in unit test
  tests/unit/active/test_active_bcast_put.cc
  tests/unit/active/test_active_send.cc
  tests/unit/active/test_active_send_put.cc
Labels: 1.0.0, 1.0.0-beta.3

#518 517 remove extraneous commas
  tests/unit/collection/test_broadcast.cc
  tests/unit/collection/test_construct.cc
  tests/unit/collection/test_construct_idx_fst.cc
  tests/unit/collection/test_construct_idx_snd.cc
  tests/unit/collection/test_construct_no_idx.cc
  tests/unit/collection/test_index_types.cc
  tests/unit/collection/test_send.cc
  tests/unit/location/test_location.cc
  tests/unit/memory/test_memory_active.cc
Labels: 1.0.0-beta.3

#520 519 fail on segfault
  cmake/test_vt.cmake
  tests/CMakeLists.txt
Labels: 1.0.0-beta.3

#514 511 only create trace directory when runtime tracing is enabled
  src/vt/runtime/runtime.cc
Labels: 1.0.0, 1.0.0-beta.3

#525 524 remove signedness warnings
  src/vt/messaging/irecv_holder.h
Labels: 1.0.0-beta.3
