Repository DARMA-tasking/vt, pull requests merged in 2020-07, with the labels that each got.

#888 854 - Outside Scheduler Loop Events
  src/vt/scheduler/scheduler.cc
  src/vt/scheduler/scheduler.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
  src/vt/trace/trace_user.h
Labels: 1.0.0-beta.9

#899 886 - Add missing MPI-allowed guard in recvDataMsgBuffer
  src/vt/messaging/active.cc
Labels: 1.0.0-beta.9, type: bugfix

#902 867 - Exclude PMPI calls for OpenMPI 1.10 compatibility
  src/vt/pmpi/generate_mpi_wrappers.pl
Labels: 1.0.0-beta.9, type: bugfix

#906 905 add proper cmake depends for MPI guards generation
  src/CMakeLists.txt
Labels: 1.0.0-beta.9

#936 935 CI: add label trigger for extended testing
  .github/workflows/dockerimage-intel-18-ubuntu-mpich-extended.yml
  scripts/workflows.ini
Labels: runextendedtests
