Repository DARMA-tasking/vt, pull requests merged in 2020-06, with the labels that each got.

#809 808 Checkpoint/Restart collection
  src/vt/vrt/collection/collection_directory.h
  src/vt/vrt/collection/manager.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/collection/staged_token/token.h
  tests/unit/collection/test_checkpoint.cc
Labels: 1.0.0-beta.9

#836 #835 skip MPI guard positive test in release builds
  tests/unit/runtime/test_mpi_access_guards.cc
Labels: 1.0.0-beta.9

#838 837 Rewrite README.md
  README.md
Labels: 1.0.0-beta.9

#847 Merge 1.0.0 beta.9 proposed proposed update into proposed update
  ci/test_cpp.sh
  src/vt/runtime/runtime.cc
  src/vt/serialization/messaging/serialized_messenger.impl.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/proxy/base_collection_elm_proxy.h
Labels: Release

#843 840 Fix asan issues and CI issues with return code
  ci/test_cpp.sh
  cmake/define_build_types.cmake
  src/vt/collective/basic.cc
  src/vt/serialization/messaging/serialized_messenger.impl.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/proxy/base_collection_elm_proxy.h
  src/vt/worker/worker_group.impl.h
Labels: 1.0.0-beta.9

#845 844: Fix bug accessing theSched() when runtime is inactive
  src/vt/runtime/runtime.cc
Labels: 1.0.0-beta.9

#849 848 Stop overriding the user's zoltan config
  cmake/define_build_types.cmake
  cmake/load_zoltan_package.cmake
Labels: 1.0.0-beta.9

#852 851 Fix param.cc example compilation under CUDA
  examples/hello_world/param.cc
Labels: 1.0.0-beta.9

#757 713 Rewrite buffering code in collection manager to fix bugs
  src/vt/vrt/collection/manager.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/collection/messages/system_create.h
  src/vt/vrt/collection/op_buffer.h
Labels: 1.1.0

#662 567 improved arg handling
  src/vt/configs/arguments/argparse.h
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/runtime/runtime.cc
  src/vt/runtime/runtime.h
  src/vt/runtime/runtime_banner.cc
Labels: 1.1.0

#855 #850 Downgrade perl dependency to 5.16.3 (affected MPI guard-enabled builds)
  src/vt/pmpi/generate_mpi_wrappers.pl
Labels: 1.0.0-beta.9

#862 #845 Log events 'between' top-level schedulers; can cover when VT is not running.
  src/vt/runtime/runtime.cc
  src/vt/scheduler/scheduler.cc
  src/vt/scheduler/scheduler.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
  src/vt/trace/trace_user.h
Labels: 1.0.0-beta.9

#863 #853 Tests only: fix race condition in scheduler loop tests
  tests/unit/scheduler/test_scheduler_loop.cc
Labels: 1.0.0-beta.9
