Repository DARMA-tasking/vt, pull requests merged in 2020-04, with the labels that each got.

#722 721 Trace flush bug fixes
  src/vt/messaging/active.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
  src/vt/trace/trace_common.h
  src/vt/trace/trace_user.h
  src/vt/trace/trace_user_event.cc
  src/vt/trace/trace_user_event.h
  src/vt/vrt/collection/balance/lb_invoke/invoke.cc
  src/vt/vrt/collection/balance/lb_invoke/invoke.h
  src/vt/vrt/collection/manager.cc
Labels: 1.0.0-beta.6

#755 #754 Add traverse methods for indices in chain set
  src/vt/messaging/collection_chain_set.h
Labels: 1.0.0-beta.6

#747 #647 fix format-string type warnings
  src/vt/trace/trace.cc
  src/vt/vrt/collection/balance/proc_stats.cc
Labels: 1.1.0

#761 760 Tutorial: work around bug in collection buffering
  tutorial/tutorial_2b.h
Labels: 1.0.0-beta.6

#768 767 irecv holder fix
  src/vt/messaging/irecv_holder.h
Labels: 1.0.0-beta.7

#773 772 user trace components
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/event/event.cc
  src/vt/event/event.h
  src/vt/messaging/active.cc
  src/vt/messaging/active.h
  src/vt/messaging/irecv_holder.h
  src/vt/runtime/runtime.cc
Labels: 1.0.0-beta.7

#766 765 location hops fix
  src/vt/topos/location/location.h
  src/vt/topos/location/location.impl.h
  src/vt/topos/location/message/msg.h
  tests/unit/location/test_hops.cc
Labels: 1.0.0-beta.7

#775 774 irecv test right away
  src/vt/messaging/active.cc
  src/vt/messaging/irecv_holder.h
Labels: 1.0.0-beta.7

#770 769 gossip bugs
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Labels: 1.0.0-beta.7

#779 778 always flush
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/configs/debug/debug_print.h
  src/vt/runtime/runtime.cc
Labels: 1.0.0-beta.7

#777 776 after lb stats fix
  src/vt/vrt/collection/balance/baselb/baselb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
Labels: 1.0.0-beta.7

#720 #708 vector balancing, part 1
  src/vt/vrt/collection/balance/elm_stats.cc
  src/vt/vrt/collection/balance/elm_stats.h
  src/vt/vrt/collection/balance/elm_stats.impl.h
Labels: 1.0.0-beta.7

#771 Merge 1.0.0 beta.7 to proposed update
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/configs/debug/debug_print.h
  src/vt/event/event.cc
  src/vt/event/event.h
  src/vt/messaging/active.cc
  src/vt/messaging/active.h
  src/vt/messaging/irecv_holder.h
  src/vt/runtime/runtime.cc
  src/vt/topos/location/location.h
  src/vt/topos/location/location.impl.h
  src/vt/topos/location/message/msg.h
  src/vt/vrt/collection/balance/baselb/baselb.cc
  src/vt/vrt/collection/balance/elm_stats.cc
  src/vt/vrt/collection/balance/elm_stats.h
  src/vt/vrt/collection/balance/elm_stats.impl.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
Labels: Release

#782 #781 Clear out pointless templates
  src/vt/vrt/collection/balance/elm_stats.h
  src/vt/vrt/collection/migrate/manager_migrate_attorney.h
  src/vt/vrt/collection/types/base.h
  src/vt/vrt/collection/types/base.impl.h
  src/vt/vrt/collection/types/indexable.h
  src/vt/vrt/collection/types/indexable.impl.h
  src/vt/vrt/collection/types/migratable.cc
  src/vt/vrt/collection/types/migratable.fwd.h
  src/vt/vrt/collection/types/migratable.h
  src/vt/vrt/collection/types/migratable.impl.h
Labels: 1.0.0-beta.8

#785 Merge 1.0.0 beta.7 proposed update into 1.0.0
  src/vt/collective/reduce/operators/default_op.impl.h
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/configs/debug/debug_print.h
  src/vt/event/event.cc
  src/vt/event/event.h
  src/vt/group/collective/group_info_collective.cc
  src/vt/messaging/active.cc
  src/vt/messaging/active.h
  src/vt/messaging/irecv_holder.h
  src/vt/pipe/callback/proxy_send/callback_proxy_send.h
  src/vt/pipe/pipe_manager_tl.h
  src/vt/runtime/runtime.cc
  src/vt/termination/termination.cc
  src/vt/topos/location/location.h
  src/vt/topos/location/location.impl.h
  src/vt/topos/location/message/msg.h
  src/vt/vrt/collection/balance/baselb/baselb.cc
  src/vt/vrt/collection/balance/elm_stats.cc
  src/vt/vrt/collection/balance/elm_stats.h
  src/vt/vrt/collection/balance/elm_stats.impl.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
  src/vt/vrt/collection/proxy.h
  src/vt/vrt/proxy/collection_proxy.h
  src/vt/vrt/proxy/collection_proxy.impl.h
Labels: Release
