Repository DARMA-tasking/vt, pull requests merged in 2020-02, with the labels that each got.

#661 #659: Eliminate unused (member/capture) variables that Clang 7 warns about
  examples/collection_insert.cc
  examples/jacobi2d_vt.cc
  examples/reduce.cc
  examples/simple_collection_reduce.cc
Labels: 1.0.0-beta.5

#664 663 trace fix warnings on gcc-7
  src/vt/trace/trace.cc
  src/vt/trace/trace_log.h
Labels: 1.0.0-beta.5

#669 #668: signed vs unsigned warnings with gcc 9.2.0 in test_term_cleanup
  tests/unit/termination/test_term_cleanup.cc
Labels: 1.0.0-beta.5

#642 642 simplify trace pairs
  src/vt/parameterization/parameterization.h
  src/vt/rdma/state/rdma_state.cc
  src/vt/runnable/collection.impl.h
  src/vt/runnable/general.impl.h
  src/vt/runnable/vrt.impl.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
Labels: 1.1.0

#674 673 print stats after
  src/vt/vrt/collection/balance/baselb/baselb.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
Labels: 1.0.0-beta.5

#678 676 trace fix user event cur event
  src/vt/trace/trace.cc
Labels: 1.0.0-beta.5

#683 682 fix user event trace incrementing
  src/vt/trace/trace.cc
Labels: 1.0.0-beta.5

#640 #631 trace system events
  src/vt/collective/barrier/barrier.cc
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/handler/handler.cc
  src/vt/handler/handler.h
  src/vt/messaging/active.cc
  src/vt/messaging/active.h
  src/vt/messaging/active.impl.h
  src/vt/messaging/envelope/envelope_base.h
  src/vt/messaging/envelope/envelope_get.h
  src/vt/messaging/envelope/envelope_get.impl.h
  src/vt/messaging/envelope/envelope_set.h
  src/vt/messaging/envelope/envelope_set.impl.h
  src/vt/messaging/envelope/envelope_setup.impl.h
  src/vt/runnable/collection.h
  src/vt/runnable/collection.impl.h
  src/vt/runnable/general.impl.h
  src/vt/runtime/runtime.cc
  src/vt/serialization/messaging/serialized_messenger.h
  src/vt/serialization/messaging/serialized_messenger.impl.h
  src/vt/termination/dijkstra-scholten/comm.cc
  src/vt/termination/termination.cc
  src/vt/topos/location/location.impl.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
  src/vt/vrt/collection/manager.h
  src/vt/vrt/collection/manager.impl.h
  src/vt/vrt/collection/messages/user.h
  src/vt/vrt/collection/messages/user.impl.h
  tests/unit/scheduler/test_scheduler_priorities.cc
Labels: 1.1.0

#690 689 New tracing enable specification file
  src/CMakeLists.txt
  src/vt/configs/arguments/args.cc
  src/vt/configs/arguments/args.h
  src/vt/runtime/runtime.cc
  src/vt/runtime/runtime_holder.h
  src/vt/trace/file_spec/spec.cc
  src/vt/trace/file_spec/spec.h
  src/vt/trace/trace.cc
  src/vt/trace/trace.h
  src/vt/vrt/collection/balance/lb_invoke/invoke.cc
  src/vt/vrt/collection/balance/lb_invoke/invoke.h
  tests/CMakeLists.txt
  tests/unit/trace/test_trace_spec_reader.cc
Labels: 1.0.0-beta.5

#693 691 GossipLB: re-compute PMF each assignment, loosen underloaded
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Labels: 1.0.0-beta.5

#698 697 Trace: fix hiding member warning
  src/vt/trace/trace_log.h
Labels: 1.0.0-beta.5

#700 699 Fix missing static declarations
  src/vt/lb/instrumentation/entity.cc
Labels: 1.0.0-beta.5

#701 696 HierarchicalLB: Add strategy argument to LB file
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
  src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
  src/vt/vrt/collection/balance/read_lb.h
Labels: 1.0.0-beta.5

#704 694 Fix termination segfault caused by TermDS being erased while running
  src/vt/termination/termination.cc
Labels: 1.0.0-beta.6

#711 710 Termination: use DS-epoch by default in dep send chain
  src/vt/messaging/dependent_send_chain.h
Labels: 1.0.0-beta.6
