Repository DARMA-tasking/vt, pull requests merged in 2021-04, with the labels that each got.

#1349 1279 gossiplb inform and decide have bugs - release branch
  src/vt/vrt/collection/balance/gossiplb/gossip_msg.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Labels: 1.0.0-beta.10.4.1

#1371 1366 LB strategy name can skip validation
  src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
Labels: 1.0.2

#1325 1006: GroupCollective setup races with continuation registration code
  src/vt/configs/debug/debug_print.h
  src/vt/group/collective/group_info_collective.cc
  tests/unit/group/test_group.extended.cc
  tests/unit/termination/test_term_dep_send_chain.cc
Labels: 1.0.2

#1370 1369 implement additional gossiplb ordering
  src/vt/vrt/collection/balance/baselb/baselb.cc
  src/vt/vrt/collection/balance/baselb/baselb.h
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
  tests/unit/lb/test_gossiplb.nompi.cc
Labels: 1.0.2

#1388 1387 GossipLB fanout type is too small
  src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
  src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Labels: 1.0.2

#1130 1079: Rewrote sucessor to parent epoch in all associated files
  src/vt/termination/epoch_tags.cc
  src/vt/termination/epoch_tags.h
  src/vt/termination/termination.cc
  src/vt/termination/termination.h
  src/vt/vrt/collection/manager.impl.h
  tests/unit/termination/test_term_cleanup.cc
  tests/unit/termination/test_termination_action_nested_collect.cc
  tests/unit/termination/test_termination_action_nested_rooted.cc
Labels: task-8

#1397 1385: Fix nvcc warning about sign mismatch
  src/vt/trace/trace_common.h
Labels: 1.0.2
